name: MicroSensor

on: [push]

jobs:
  microsensor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TMS
        uses: actions/checkout@v2


      - name: Perform static source code analysis
        uses: microsensorproject/microsensor@development