name: Test MSANose Action

on: [push]

jobs:
  msanose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FudanSELab/train-ticket
        uses: actions/checkout@v2

      - name: Check GITHUB_WORKSPACE content.
        run: |
          pwd
          ls -l
          ls -l $GITHUB_ACTION_PATH

      # Run the analysis on the specified directory.
      - name: Perform the smells analysis.
        id: analysis
        uses: edson-a-soares/msanose-action@development
        with:
          analysis_directory: $GITHUB_WORKSPACE

      # Collect the analysis output.
      - name: Get the analysis output (e.g., report)
        run: echo "${{ steps.analysis.outputs.report }}"
